#!/bin/sh

# Author: z1rov

super + {1-6}
    bspc desktop -f ^{1-6}

super + shift + {1-6}
    bspc node -d ^{1-6}

super + Return
    sh -c 'cd ~ && exec kitty'

super + r
    RiceEditor

super + 8
    kitty -e kon start

super + 9
    kitty --class FloatingTerm --title "HTB VPN" --override initial_window_width=400 --override initial_window_height=300 -e /usr/bin/htb-vpn

super + s
    sh -c 'DIR=~/Pictures/Clipboard; mkdir -p "$DIR"; \
    n=$(ls "$DIR" 2>/dev/null | grep -Eo "^img[0-9]+\.png$" | sed "s/[^0-9]//g" | sort -n | tail -1); \
    [ -z "$n" ] && n=0; next=$((n+1)); \
    IMG="$DIR/img$next.png"; \
    flameshot full -p "$IMG" && xclip -selection clipboard -t image/png -i "$IMG" && notify-send "Screenshot saved and copied" && pkill flameshot'

super + shift + s
    sh -c 'DIR=~/Pictures/Clipboard; mkdir -p "$DIR"; \
    n=$(ls "$DIR" 2>/dev/null | grep -Eo "^img[0-9]+\.png$" | sed "s/[^0-9]//g" | sort -n | tail -1); \
    [ -z "$n" ] && n=0; next=$((n+1)); \
    IMG="$DIR/img$next.png"; \
    flameshot gui -p "$IMG" && xclip -selection clipboard -t image/png -i "$IMG" && notify-send "Screenshot saved and copied"'

ctrl + super + alt + {p,r,q,l,k,s}
    {systemctl poweroff, systemctl reboot, bspc quit, ScreenLocker, xkill, SoftReload}

XF86MonBrightness{Up,Down}
    sh brightness {up,down}

XF86Audio{RaiseVolume,LowerVolume,Mute}
    volume{ --inc, --dec, --toggle}

XF86AudioPlay
    playerctl play-pause

XF86AudioNext
    playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86AudioMicMute
    pactl set-source-mute @DEFAULT_SOURCE@ toggle && notify-send "Mic Toggle"

XF86Phone
    notify-send "Call button (not assigned)"

XF86Hangup
    notify-send "Hangup call (not assigned)"

XF86WLAN
    sh -c 'rfkill toggle wifi; notify-send "WiFi toggle"'

XF86Bluetooth
    sh -c 'rfkill toggle bluetooth; notify-send "Bluetooth toggle"'

super + alt + r
    bspc wm -r

super + Escape
    pkill -USR1 -x sxhkd

super + x
    bspc node -c

ctrl + Tab
    bspc node @/ --rotate {90,-90}

super + ctrl + r
    bspc node @/ --rotate 90

super + {Left,Right}
    bspc desktop -f {prev,next}

super + f
    bspc desktop -l next

super + d
    rofi -show drun -theme $HOME/.config/rofi/config.rasi

alt + Left
    bspc node -z right -20 0 || bspc node -z left -20 0

alt + Right
    bspc node -z right 20 0 || bspc node -z left 20 0

alt + Up
    bspc node -z bottom 0 -20 || bspc node -z top 0 -20

alt + Down
    bspc node -z bottom 0 20 || bspc node -z top 0 20

super + ctrl + {h,v,q}
    bspc node -p {east,south,cancel}

super + ctrl + {h,l}
    bspc node @parent -r {-0.1,+0.1}

super + ctrl + x
    bspc query -N -d | xargs -I id -n 1 bspc node id -c
